import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from 'react';
import localFont from "next/font/local";
import {Alegreya} from "next/font/google"

const monCheri = localFont({
  src: "./fonts/MonCheri.otf",
  variable: "--font-moncheri",
  weight: "400",
});

const alegreya = Alegreya({
  subsets: ['latin'],
  variable: '--font-alegreya',
  weight: ["400", "500", "600"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: ReactNode }) {
  return (
    <html lang="en">
    <body className={`${monCheri.variable} ${alegreya.variable} antialiased`}>
    {children}
    </body>
    </html>
  );
}
